### ISSUE TITLE
NaNs in HIF

### ISSUE THREAD

**Issue by brendapraggastis** [pszufe/HIF-standard#10]
How should the library handle NaNs? If for example the dataset is tabular and a hypergraph is created such that most of the objects have property P but for. some the property is assigned NaN or [] or {}. How should this be formatted in HIF? This came up because I took the HGX contacts_high_school dataset from json to an hnx Hypergraph to HIF and found I couldn't use json.dump without reformatting NaNs to empty strings. Should that be the default behavior?

**Comment by colltoaction** [comment]
We agreed it is important for each library to handle absence of float value instead of using the "NaN" string
