### ISSUE TITLE
Read Write with json dump and load

### ISSUE THREAD

**Issue by brendapraggastis** [pszufe/HIF-standard#12]
When attempting to write hif to json files I threw errors on empty dictionaries. To avoid this, we might want to implement a file save/dump keyword in to_hif and from_hif. Here are some of the issues I would like to think about:

1. How to handle NaNs and [] and {}
2. How to limit objects to reasonable amount and minimize security risks with strings
Look at options in 
[https://docs.python.org/3/library/json.html](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.python.org%2F3%2Flibrary%2Fjson.html&data=05%7C02%7CBrenda.Praggastis%40pnnl.gov%7C10b20d44c13942c1bdb208dcbd4dab61%7Cd6faa5f90ae240338c0130048a38deeb%7C0%7C0%7C638593388493988960%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=gdw6PPCQWsRQ3x0WaTPALp4BGM1zCTpEVeG45yLAZeo%3D&reserved=0)
3. Build in HIF dump and load functions into to and from hif.
 
I would like to handle these internally using Python’s json library rather than an external library like simplejson. I will try to work on this next week, but if anyone has suggestions let me know.

**Comment by colltoaction** [comment]
This is done as far as this repository is concerned.
