### ISSUE TITLE
Handling ASC

### ISSUE THREAD

**Issue by FraLotito** [pszufe/HIF-standard#22]
I was trying to handle abstract simplicial complexes. Reading the data is straightforward since we have the ASC property, so I know to account for subset closure and generate all necessary sub-hyperedges. For dumping to file, though, I’m unsure—do you typically write out every hyperedge or just the maximal ones?

**Comment by nwlandry** [comment]
Hi @FraLotito --- in XGI we write maximal faces plus all subfaces with attributes. Here's the [module](https://github.com/xgi-org/xgi/blob/main/xgi/readwrite/hif.py) in XGI.

**Comment by FraLotito** [comment]
Thanks @nwlandry I will follow the same logic
