### ISSUE TITLE
Support JSON schema standard? 

### ISSUE THREAD

**Issue by pszufe** [pszufe/HIF-standard#4]
There is a JSON schema standard:
https://json-schema.org/learn/getting-started-step-by-step

I believe the code #3  that is being developed by @nwlandry should at least include such definition. 

The JSON schema has validators for most of programming languages. 
https://json-schema.org/implementations

I would like to open a discussion about using such validator in the code developed by @nwlandry 

I would make the maintenance of HIF standard more comfortable and the standard itself would be more easy to integrate across programming languages.

**Comment by nwlandry** [comment]
Agreed --- the checker is a starting point. But it can also check things that (to my knowledge) a schema can't check. For example, if it is best practice to only have maximal edges in the JSON for the simplicial complex, a schema can't check that.

**Comment by brendapraggastis** [comment]
I think the included edges may depend on the existence of additional data on them. Some sub-edges may have data, in which case even if your hypergraph is an ASC, more than the top level edges would need to be stored in the HIF string.
Also, validation by a json checker is magnitudes faster than what python can do line by line, so validating based on a the schema would probably be more universal than validating to library specific requirements in Python.

**Comment by brendapraggastis** [comment]
[hif_schema2.json](https://github.com/user-attachments/files/16514011/hif_schema2.json)

**Comment by brendapraggastis** [comment]
The hif_schema2.json is my current submission for a schema. We can discuss next week.
